---
- name: Install Jenkins
  hosts: jenkins_slave_vm
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jre
        state: present

    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Change permissions for docker.sock
      file:
        path: /var/run/docker.sock
        mode: '0777'