---
- name: Install Jenkins
  hosts: jenkins_vm
  become: yes

  vars:
    jenkins_repo_key: "https://pkg.jenkins.io/debian/jenkins.io.key"
    jenkins_repo_url: "https://pkg.jenkins.io/debian"
  tasks:
    - name: Add Jenkins repository key
      apt_key:
        url: "{{ jenkins_repo_key }}"
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb {{ jenkins_repo_url }} binary/"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
