---
- name: Install Jenkins
  hosts: jenkins_slave_vm
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jre
        state: present