---
- name: Install Docker and SonarQube using Ansible
  hosts: sonarqube_vm
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reinitialize group membership
      shell: newgrp docker

    - name: Change permissions for docker.sock
      file:
        path: /var/run/docker.sock
        mode: '0777'

    - name: Run SonarQube container
      docker_container:
        name: sonar
        image: sonarqube:lts-community
        ports:
          - "9000:9000"
        state: started
